### ISSUE TITLE
Unexpected Token '?'

### ISSUE THREAD

**Issue by TobiTenno** [roydukkey/clean-package#16]
I'm running clean-package in our prepublishOnly script, but I'm getting errors on node 15 w/ npm 7.7.6:
```sh
> warframe-items@1.1252.69 prepublishOnly /home/runner/work/warframe-items/warframe-items
> npm_config_yes=true npx clean-package

npx: installed 14 in 2.59s
Unexpected token '?'
```

this is during a semantic-release run using clean-package before packing.

[actions run](https://github.com/WFCD/warframe-items/runs/4940203407?check_suite_focus=true) | [script](https://github.com/WFCD/warframe-items/blob/master/package.json#L12)

**Comment by roydukkey** [comment]
@TobiTenno Can you provide an example to reproduce the issue?

**Comment by TobiTenno** [comment]
yeah, i linked to the action and the script.

**Comment by roydukkey** [comment]
The error indicates that `@semantic-release/npm` is the cause of the issue, which is not used by clean-package.

This commit (https://github.com/WFCD/warframe-items/commit/f5344b4e4fccb1a8fd5b5952ed8650182634d67a) didn't change anything with clean-package, and the prior commits didn't fail, so I'm inclined to believe this issue is external to clean-package.

If you're able to provide steps to reproduce the issue, I'll graciously continue diagnosis.

**Comment by TobiTenno** [comment]
Ok, I'll keep investigating from that angle.
